---
title: "Homework 1"
author: Matthew Angulo
output: github_document
---

This is my solution to HW1

```{r}
library(tidyverse)
```


## Problem 1

Create a data frame with the specified elements.

```{r create_df}
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low","low","low","med", "med", "med", "med", "high", "high", "high"))
  )

prob1_df
```

Take the mean of each variable in my data frame

```{r mean_pull_var}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical but not character or factor. 

Now converting variables to numeric.

```{r try_numeric}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))

```

Character variables cannot be converted to numeric.




```{r convert_logical}
as.numeric(pull(prob1_df, samp_gt_0))*pull(prob1_df, samp)
as.factor(pull(prob1_df, samp_gt_0))*pull(prob1_df, samp)
as.numeric(as.factor(pull(prob1_df, samp_gt_0)))*pull(prob1_df, samp)
```

Factors of logical variables cannot be multiplied by numbers  


## Problem 2

```{r}
install.packages("palmerpenguins")
data("penguins", package = "palmerpenguins")
```
 
 